### ISSUE TITLE
OutOfMemory in manager container when using default mem/cpu limit 

### ISSUE THREAD

**Issue by wmellouli** [Carrefour-Group/elastic-phenix-operator#22]
Manager container is generally in `OutOfMemory` when using default `memory` & `cpu` `request`/`limit` values.
Should add more memory for default values:

```
        name: manager
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
```

![oom-epo](https://user-images.githubusercontent.com/2271328/121158390-a10c3900-c84a-11eb-9bc9-b6c7b757b800.png)
